### ISSUE TITLE
how to access private chennels with token from unity

### ISSUE THREAD

**Issue by virtouso** [pusher/pusher-websocket-unity#2]
hi.
im looking for a way to join to private channels to prevent unauthenticated users to join private channels. as i searched there is channel subscription with token option but dont know its implemented in the api or if implemented how can i use it.

**Comment by damdo** [comment]
Hey @virtouso,
In order to have private channels you need to setup two components correctly:
1) the Server Side:
https://pusher.com/docs/channels/server_api/authenticating-users

2) the Client Side (.NET/Unity):
https://github.com/pusher/pusher-websocket-dotnet#event-based-1
