### ISSUE TITLE
self hosted pusher support.

### ISSUE THREAD

**Issue by ycgambo** [pusher/pusher-websocket-unity#21]
There are several open source solutions like [laravel websockets](https://beyondco.de/docs/laravel-websockets/basic-usage/pusher) out there which supports self hosted pusher service. 

How about expose more PusherOptions? especially HOST and PORT.

**Comment by ben-pusher** [comment]
Thanks for sharing your feedback, this is something we will look at and consider. 
However, it is worth noting that laravel websockets is a Pusher replacement service: as such we do not guarantee support for laravel websockets. You may have more success forking this library and implementing the changes you require there.
