### ISSUE TITLE
Any plans about 2.1.0?

### ISSUE THREAD

**Issue by ycgambo** [pusher/pusher-websocket-unity#24]
[pusher-websocket-dotnet](https://github.com/pusher/pusher-websocket-dotnet) 2.1.0 has released, any plans to follow that update?

**Comment by elverkilde** [comment]
hi @ycgambo, sorry for the late reply. We have been working on a 2.1 migration, but we've hit some problems with the new dependency, NaCL.

You can track progress here: #26

**Comment by ycgambo** [comment]
I'm currently using Nuget For Unity to manage Pusher Websocket Dotnet 2.1.0, which works fine

**Comment by elverkilde** [comment]
Oh, interesting, would you be able to share more details? I can try Nuget for Unity, but I have pretty limited understanding of this eco system to be honest. So far I have just tried updating the DLLs, but they seem to be incompatible.

**Comment by ycgambo** [comment]
Nuget For Unity provides a UI panel to mange dependencies.
Seems like it can identify which dll to import

![image](https://user-images.githubusercontent.com/23355083/119103780-1fe13380-ba4e-11eb-92ad-31e081e1c002.png)

pusher already released .net packages
this is how my project directory looks when using Nuget For Unity

![image](https://user-images.githubusercontent.com/23355083/119103104-5bc7c900-ba4d-11eb-9740-e6670c786b62.png)

**Comment by vincent-savysoda** [comment]
Any updates on updating this plugin?

**Comment by benw-pusher** [comment]
This library has been updated to use pusher-websocket-dotnet 2.1 - https://github.com/pusher/pusher-websocket-unity/releases/tag/2.1.0%2B211120.
