### ISSUE TITLE
How to use private channel?

### ISSUE THREAD

**Issue by jeansebastienZ** [pusher/pusher-websocket-unity#29]
Hello , i'm trying to understand something .
If an user want to trigger an event on a channel he can't if the channel is not private ?
So basically the public channel are only - server -> client . Like pushing a notifications to all user.

But basically if i want to push an even from client -> server : HOW TO ?
I've already read this one :
 [https://pusher.com/docs/channels/server_api/authenticating-users](https://pusher.com/docs/channels/server_api/authenticating-users) 

But to understand how to set up that's clearly not easy.
My aim was to use pusher to let client send message between them even by paying pusher monthly price , but what i understand now is that for private channel i need to set up something more ? 
Could someone help please . 

By the way i'm using unity , so .NET , i precise as the pusher documentation get few .net example .

Regards

**Comment by twomedia** [comment]
For security reasons, message sending should only be done by your server. You should setup an API endpoint for the client to hit to send those messages. That way you can have control over the messages sent & the authentication of that user. If you went with the approach you described then anyone could decompile your app or read the memory values to get the Pusher private key and do anything they like.

**Comment by benw-pusher** [comment]
> but what i understand now is that for private channel i need to set up something more ?
This is correct: in order for clients to subscribe to private channels you would need to provide an auth endpoint that authenticates the subscription request. 

It is not possible to trigger client events without using an authenticated channel (private or presence channels).
