### ISSUE TITLE
Calling Channel.Unsubscribe causes client to freeze

### ISSUE THREAD

**Issue by vincent-savysoda** [pusher/pusher-websocket-unity#36]
I just tried updating from V1 to V2 of the Pusher client and I am currently encountering an issue with calling the Channel.Unsubscribe method. I noticed that the method has changed to a Task instance? Is there a different way to use this now that I'm not aware of?

**Comment by vincent-savysoda** [comment]
I had to switch to using UnsubscribeAsync instead and converting the original method calling it into an async Task method.

**Comment by benjamin-tang-pusher** [comment]
Just out of curiosity, which version of Unity are you using?
