### ISSUE TITLE
Update to Newtonsoft.json in the future?

### ISSUE THREAD

**Issue by TsukadaMas** [pusher/pusher-websocket-unity#37]
Hi, I noticed in the project that pusher used Newtonsoft Version 11 is there any plans to update the version of pusher to 12 or 13 as those are the most current date versions of Newtonsoft?

**Comment by benjamin-tang-pusher** [comment]
Hi,

My Unity project using PusherClient 2.1.0 uses Newtonsoft Json 12. Are you on an older version of PusherClient?

**Comment by TsukadaMas** [comment]
ya. fortunately, the project I was working on allowed me to remove it because it was being handled by native instead of unity
