### ISSUE TITLE
Error when subscribing to channels from ios platform app

### ISSUE THREAD

**Issue by RenataSaenz** [pusher/pusher-websocket-unity#47]
I'm have the following 2 errors when using the app in ios:

1- Error: ERROR An unexpected error was detected when performing the operation 'Subscribe to events':
System.Reflection.Emit.DynamicMethod::.ctor

PusherClient.ErrorEventHandler:Invoke(Object, PusherException)
PusherClient.Pusher:InvokeErrorHandler(PusherException)
System.Threading.ThreadPoolWorkQueue:Dispatch()

2- Error: ERROR Subscribe failed for channel 'events':
One or more errors occurred.

PusherClient.ErrorEventHandler:Invoke(Object, PusherException)
PusherClient.Pusher:InvokeErrorHandler(PusherException)
System.Threading.ThreadPoolWorkQueue:Dispatch()

The configuration says i should set the Scripting Runtime Version to .NET 4.x Equivalent. But this is not supported by ios. What should i do?

**Comment by benjamin-tang-pusher** [comment]
Just to eliminate if this is a .net version issue, if you target a desktop app (Windows or Mac), can you get your game running?

**Comment by benjamin-tang-pusher** [comment]
Closing due to no response.
