### ISSUE TITLE
[FR] Drop support for editor versions prev 2020.x

### ISSUE THREAD

**Issue by StephenHodgson** [pusher/pusher-websocket-unity#48]
To better support newer versions of the package it might be easier to drop support for older unsupported versions of the editor older than 2020.x

One key advantage is using Unity's Netwonsoft.Json package as as dep, and taking advantage of newer language support without having to manually include nuget dlls in the package directly.

**Comment by StephenHodgson** [comment]
Bump

**Comment by benjamin-tang-pusher** [comment]
We've dropped support for the older versions.
