### ISSUE TITLE
[FR] Link.xml should be included in package by default

### ISSUE THREAD

**Issue by StephenHodgson** [pusher/pusher-websocket-unity#49]
The IL2CPP extra steps outlined in the documentation could be removed if the link.xml file is included directly in the project, thus simplifying usage for consumers of the package.

**Comment by benjamin-tang-pusher** [comment]
Thanks for the recommendation, but we will leave it as is. I will close this issue.

**Comment by StephenHodgson** [comment]
it wasn't a recommendation, it removes a manual step that devs have to take when importing this package.

Better to do it on your end, to remove a manual setup step.
