### ISSUE TITLE
[FR] Update docs to add OpenUPM installation method 

### ISSUE THREAD

**Issue by StephenHodgson** [pusher/pusher-websocket-unity#50]
Git installation method isn't ideal when you have packages with multiple dependencies, and OpenUPM properly uses Unity's package manager to resolve deps for packages. 

I went ahead and added this package to [OpenUPM](https://openupm.com/packages/com.pusher.pusherwebsocketunity/)

```cli
openupm add com.pusher.pusherwebsocketunity
```

**Comment by benjamin-tang-pusher** [comment]
Thanks for adding the repo to their repository. I will close this issue.
